version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:871849853672:task-definition/CICD-taskdefination:1"
        LoadBalancerInfo:
          ContainerName: "myapp"
          ContainerPort: 8080
