version: 0.2

phases:
  pre_build:
    commands:
       - echo check version
       - mvn -version
       - aws --version
       - docker version
       - echo login to ECR
       - put ecr login command here
       
  build:
    commands:
       - echo Build started on `date`
       - echo Running maven commands
       - echo $CODEBUILD_BUILD_NUMBER
       - mvn clean install package
       - echo Building Docker Images
       - cp Dockerfile webapp/target/Dockerfile
       - cd webapp/target
       - docker build -t cicd_ecr:$CODEBUILD_BUILD_NUMBER .
       - docker tag cicd_ecr:$CODEBUILD_BUILD_NUMBER 871849853672.dkr.ecr.us-east-1.amazonaws.com/cicd_ecr:latest
       
  post_build:
    commands:
       - echo Build started on `date`
       - echo Pushing Docker Image
       - docker push 871849853672.dkr.ecr.us-east-1.amazonaws.com/cicd_ecr:$CODEBUILD_BUILD_NUMBER
    
artifacts:
  files:
    - webapp/target/webapp.war
    - Dockerfile
